#########################################
##########   Collector     ##############
#########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
  namespace : cpusdi1_20-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      name: collector-pod
      labels:
        app: collector
    spec:
      containers:
      - name: collector-container
        image: gitlab-student.centralesupelec.fr:4567/tanguy.colleville/tweetoscope_2021_11/collector
        imagePullPolicy: Always