#########################################
##########   Predictor     ##############
#########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deployment
  namespace: cpusdi1-20-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      name: predictor-pod
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor-container
        image: matthbriet/predictor:latest
        imagePullPolicy: Always